### ISSUE TITLE
Stage 2 tracking

### ISSUE THREAD

**Issue by bakkot** [leobalter/proposal-setmap-offrom#24]
This proposal achieved stage 1 at the [September 2016 meeting](https://github.com/tc39/tc39-notes/blob/master/meetings/2016-09/sept-29.md#11iic-set-map-weakset-and-weakmap-of-and-from-methods). This is a tracking issue for getting stage 2 per the [TC39 process](https://tc39.es/process-document/).

- [x] Initial spec text
- [ ] Major syntax and semantics
- [ ] Document several motivating use cases
- [x] Transfer this repo to the TC39 org
- [ ] Committee consensus
